/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/ActionBar.vue')['default']
    ArrowLeftEndOnRectangleIcon: typeof import('@heroicons/vue/24/outline')['ArrowLeftEndOnRectangleIcon']
    ArrowsPointingOutIcon: typeof import('@heroicons/vue/24/outline')['ArrowsPointingOutIcon']
    ArrowsUpDownIcon: typeof import('@heroicons/vue/24/outline')['ArrowsUpDownIcon']
    ArrowUturnLeftIcon: typeof import('@heroicons/vue/24/outline')['ArrowUturnLeftIcon']
    ArrowUturnRightIcon: typeof import('@heroicons/vue/24/outline')['ArrowUturnRightIcon']
    Block: typeof import('./components/Block.vue')['default']
    BlocksGroup: typeof import('./components/BlocksGroup.vue')['default']
    BuildingStorefrontIcon: typeof import('@heroicons/vue/24/outline')['BuildingStorefrontIcon']
    Button: typeof import('primevue/button')['default']
    ChannelSelector: typeof import('./components/ChannelSelector.vue')['default']
    ChevronDownIcon: typeof import('@heroicons/vue/24/outline')['ChevronDownIcon']
    Cog6ToothIcon: typeof import('@heroicons/vue/24/outline')['Cog6ToothIcon']
    ComputerDesktopIcon: typeof import('@heroicons/vue/24/outline')['ComputerDesktopIcon']
    DevicePhoneMobileIcon: typeof import('@heroicons/vue/24/outline')['DevicePhoneMobileIcon']
    EyeIcon: typeof import('@heroicons/vue/24/outline')['EyeIcon']
    GlobeAsiaAustraliaIcon: typeof import('@heroicons/vue/24/outline')['GlobeAsiaAustraliaIcon']
    Header: typeof import('./components/Header.vue')['default']
    HomeIcon: typeof import('@heroicons/vue/24/outline')['HomeIcon']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LocaleSelector: typeof import('./components/LocaleSelector.vue')['default']
    MagnifyingGlassIcon: typeof import('@heroicons/vue/24/outline')['MagnifyingGlassIcon']
    PlusCircleIcon: typeof import('@heroicons/vue/24/outline')['PlusCircleIcon']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./components/Section.vue')['default']
    SectionsGroup: typeof import('./components/SectionsGroup.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Square3Stack3DIcon: typeof import('@heroicons/vue/24/outline')['Square3Stack3DIcon']
    TemplateSelector: typeof import('./components/TemplateSelector.vue')['default']
    TrashIcon: typeof import('@heroicons/vue/24/outline')['TrashIcon']
  }
}
